name: Lotus Construction Group
favicon: null
layout_spectrum: 0.9879
typography_spectrum: 0.96914
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a349a3'
    - '#000000'
    - '#cfcfcf'
    - '#818182'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
